import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/navbar";

const inter =Inter({subsets:["latin"]});

export const metadata: Metadata = {
  title: "Morph",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      
    >
      <body className={inter.className}>
        
        
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          themes={["light", "dark"]}
          >
            <Navbar/>

            <div className="container  min-h-screen pt-32 lg:pt-36 2xl:pt-44  ">
              {children}
              </div>
            
          </ThemeProvider>
          </body>
    </html>
  );
}
